runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: /
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /view-thread
  script: unused
  login: optional
  secure: optional
- url: /view-thread/.*
  script: unused
  login: optional
  secure: optional
- url: /validate-thread
  script: unused
  login: optional
  secure: optional
- url: /validate-thread/.*
  script: unused
  login: optional
  secure: optional
- url: /upvote-post
  script: unused
  login: optional
  secure: optional
- url: /upvote-post/.*
  script: unused
  login: optional
  secure: optional
- url: /post-comment
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /post-comment/.*
  script: unused
  login: optional
  secure: optional
- url: /get-threads
  script: unused
  login: optional
  secure: optional
- url: /post-thread
  script: unused
  login: optional
  secure: optional
- url: /data
  script: unused
  login: optional
  secure: optional
- url: /loginstatus
  script: unused
  login: optional
  secure: optional
- url: /nickname
  script: unused
  login: optional
  secure: optional
